# Generated by Django 2.1b1 on 2018-07-15 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contragent', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField()),
                ('trade_type', models.CharField(max_length=32)),
                ('ad_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_window', models.IntegerField()),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_method', models.CharField(max_length=32)),
                ('page_number', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedTradesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField()),
                ('trade_type', models.CharField(max_length=32)),
                ('payment_method', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField()),
                ('reference_code', models.CharField(max_length=20)),
                ('contact_id', models.IntegerField()),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_btc', models.DecimalField(decimal_places=8, max_digits=10)),
                ('fee_btc', models.DecimalField(decimal_places=8, max_digits=10)),
                ('rate_rub', models.DecimalField(decimal_places=2, max_digits=9)),
                ('seller', models.CharField(max_length=128)),
                ('buyer', models.CharField(max_length=128)),
                ('profit_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_buy_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sum_buy_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('mean_buy_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sum_sell_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sum_sell_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('mean_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('num_trades_buy', models.IntegerField(blank=True, null=True)),
                ('num_trades_sell', models.IntegerField(blank=True, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
