# Generated by Django 2.1b1 on 2018-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedTradesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField()),
                ('trade_type', models.CharField(max_length=32)),
                ('payment_method', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('released_at', models.DateTimeField()),
                ('reference_code', models.CharField(max_length=20)),
                ('contact_id', models.IntegerField()),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_btc', models.DecimalField(decimal_places=8, max_digits=10)),
                ('fee_btc', models.DecimalField(decimal_places=8, max_digits=10)),
                ('rate_rub', models.DecimalField(decimal_places=2, max_digits=9)),
                ('seller', models.CharField(max_length=128)),
                ('buyer', models.CharField(max_length=128)),
                ('profit_rub_trade', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('profit_rub_full', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_profit_fixated', models.BooleanField(default=False)),
                ('is_qiwi_blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
