# Generated by Django 2.1b1 on 2018-07-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('info_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedtradesinfo',
            name='api_key_qiwi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKeyQiwi'),
        ),
    ]
