# Generated by Django 2.1b1 on 2018-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adinfo',
            name='order_number',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
