# Generated by Django 2.1b1 on 2018-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0002_releasedtradesinfo_api_key_qiwi'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedtradesinfo',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
    ]
