# Generated by Django 2.1b1 on 2018-07-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0003_releasedtradesinfo_disputed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
