# Generated by Django 2.1b1 on 2018-07-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0003_remove_adinfo_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdInfo',
        ),
    ]
