# Generated by Django 2.1b1 on 2018-07-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180722_1832'),
        ('info_data', '0004_delete_adinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedtradesinfo',
            name='api_key_qiwi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKeyQiwi'),
            preserve_default=False,
        ),
    ]
