# Generated by Django 2.1b1 on 2018-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0005_auto_20180801_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedtransactions',
            name='transaction_id',
            field=models.CharField(max_length=32),
        ),
    ]
