# Generated by Django 2.1b1 on 2018-07-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0006_auto_20180724_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeReports',
        ),
    ]
