# Generated by Django 2.1b1 on 2018-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0007_delete_tradereports'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedtradesinfo',
            name='is_profit_fixated',
            field=models.BooleanField(default=False),
        ),
    ]
