# Generated by Django 2.1b1 on 2018-08-15 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_data', '0008_auto_20180808_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedtradesinfo',
            name='who_released_btc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
