# Generated by Django 2.1b1 on 2018-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0008_releasedtradesinfo_is_profit_fixated'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedtradesinfo',
            name='is_qiwi_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
