# Generated by Django 2.1b1 on 2018-08-17 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info_data', '0009_releasedtradesinfo_who_released_btc'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorsWorkingShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_working', models.DateTimeField()),
                ('end_working', models.DateTimeField(blank=True, null=True)),
                ('shift_duration', models.TimeField(blank=True, null=True)),
                ('number_of_deals', models.IntegerField(blank=True, null=True)),
                ('mean_deal_processing', models.TimeField(blank=True, null=True)),
                ('amount_sell_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('amount_sell_btc', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('profit_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
