# Generated by Django 2.1b1 on 2018-08-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0010_operatorsworkingshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedtradesinfo',
            name='deal_processed_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
