# Generated by Django 2.1b1 on 2018-08-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0011_releasedtradesinfo_deal_processed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorsworkingshift',
            name='shift_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
