# Generated by Django 2.1b1 on 2018-08-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0012_auto_20180817_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorsworkingshift',
            name='mean_deal_processing',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
