# Generated by Django 2.1b1 on 2018-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_data', '0013_auto_20180817_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedtradesinfo',
            name='deal_processed_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
