# Generated by Django 2.1b1 on 2018-07-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
