# Generated by Django 2.1b1 on 2018-07-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_apikeyqiwi'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyqiwi',
            name='phone_number',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
