# Generated by Django 2.1b1 on 2018-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_apikeyqiwi_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyqiwi',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
