# Generated by Django 2.1b1 on 2018-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_apikeyqiwi_for_profit_fixation'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotsettings',
            name='chat_deals',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='telegrambotsettings',
            name='chat_emerg',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='telegrambotsettings',
            name='chat_report',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
