# Generated by Django 2.1b1 on 2018-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180715_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyqiwi',
            name='proxy',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
