# Generated by Django 2.1b1 on 2018-08-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180801_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotsettings',
            name='chat_deals',
        ),
    ]
