# Generated by Django 2.1b1 on 2018-07-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_apikeyqiwi_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyqiwi',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='apikeyqiwi',
            name='bank_card',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='apikeyqiwi',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikeyqiwi',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikeyqiwi',
            name='limit_left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='apikeyqiwi',
            name='pay_system',
            field=models.CharField(blank=True, choices=[('1960', 'Visa'), ('21012', 'MasterCard')], max_length=64, null=True),
        ),
    ]
