# Generated by Django 2.1b1 on 2018-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180722_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeyqiwi',
            name='is_used',
        ),
        migrations.AddField(
            model_name='apikeyqiwi',
            name='order',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikeyqiwi',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
