# Generated by Django 2.1b1 on 2018-08-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_telegrambotsettings_chat_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeyqiwi',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='apikeyqiwi',
            name='bank_card',
        ),
        migrations.RemoveField(
            model_name='apikeyqiwi',
            name='for_profit_fixation',
        ),
        migrations.RemoveField(
            model_name='apikeyqiwi',
            name='pay_system',
        ),
    ]
