# Generated by Django 2.1b1 on 2018-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180808_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeyqiwi',
            name='balance_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
