# Generated by Django 2.1b1 on 2018-07-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180722_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=64)),
                ('chat_emerg', models.CharField(max_length=32)),
                ('chat_report', models.CharField(max_length=32)),
            ],
        ),
    ]
