# Generated by Django 2.1b1 on 2018-07-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_telegrambot_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=64)),
                ('chat_emerg', models.CharField(max_length=32)),
                ('chat_report', models.CharField(max_length=32)),
                ('proxy', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramBot',
        ),
    ]
