# Generated by Django 2.1b1 on 2018-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180722_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyqiwi',
            name='pay_system',
            field=models.CharField(blank=True, choices=[('1960', 'Visa'), ('21012', 'MasterCard'), ('466', 'Tinkoff'), ('464', 'Alfa-bank'), ('821', 'Promsvyazbank'), ('815', 'Russkii_standart')], max_length=64, null=True),
        ),
    ]
