# Generated by Django 2.1b1 on 2018-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180724_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyqiwi',
            name='pay_system',
            field=models.CharField(blank=True, choices=[('1960', 'Visa'), ('21012', 'MasterCard')], max_length=64, null=True),
        ),
    ]
