# Generated by Django 2.1b1 on 2018-07-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20180724_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeyqiwi',
            name='pay_system',
            field=models.CharField(blank=True, choices=[('1963', 'Visa'), ('21013', 'MasterCard')], max_length=64, null=True),
        ),
    ]
