# Generated by Django 2.1b1 on 2018-07-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_apikeyqiwi'),
        ('btcbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('ad_id', models.IntegerField(unique=True)),
                ('trade_direction', models.CharField(choices=[('buy-bitcoins-online', 'ONLINE_SELL'), ('sell-bitcoins-online', 'ONLINE_BUY')], max_length=64)),
                ('payment_method', models.CharField(choices=[('qiwi', 'QIWI'), ('cash-deposit', 'CASH_DEPOSIT'), ('transfers-with-specific-bank', 'SPECIFIC_BANK'), ('yandex-money', 'YANDEXMONEY')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('target_profit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('volume_max', models.IntegerField(null=True)),
                ('volume_min', models.IntegerField(null=True)),
                ('switch', models.BooleanField(default=False)),
                ('greetings_text', models.TextField(blank=True, null=True)),
                ('farewell_text', models.TextField(blank=True, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKey')),
                ('api_key_qiwi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKeyQiwi')),
                ('buy_ad_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_ad', to='btcbot.AdSetting')),
                ('sell_ad_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_ad', to='btcbot.AdSetting')),
            ],
        ),
        migrations.CreateModel(
            name='MeanBuyTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('btc_amount', models.DecimalField(decimal_places=8, max_digits=10)),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='ReportIncome',
        ),
    ]
