# Generated by Django 2.1b1 on 2018-07-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('btcbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='api_key_qiwi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKeyQiwi'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='api_key_qiwi',
            field=models.ManyToManyField(to='profiles.APIKeyQiwi'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='buy_ad_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_ad', to='btcbot.AdSetting'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='sell_ad_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_ad', to='btcbot.AdSetting'),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='telegram_bot_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.TelegramBotSettings'),
        ),
        migrations.AddField(
            model_name='adsetting',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKey'),
        ),
    ]
