# Generated by Django 2.1b1 on 2018-07-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0002_auto_20180715_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsetting',
            name='my_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='botsetting',
            name='target_profit',
            field=models.IntegerField(),
        ),
    ]
