# Generated by Django 2.1b1 on 2018-07-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180715_2042'),
        ('btcbot', '0003_auto_20180716_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsetting',
            name='api_key',
        ),
        migrations.AddField(
            model_name='botsetting',
            name='api_key',
            field=models.ManyToManyField(to='profiles.APIKey'),
        ),
        migrations.RemoveField(
            model_name='botsetting',
            name='api_key_qiwi',
        ),
        migrations.AddField(
            model_name='botsetting',
            name='api_key_qiwi',
            field=models.ManyToManyField(to='profiles.APIKeyQiwi'),
        ),
    ]
