# Generated by Django 2.1b1 on 2018-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0003_auto_20180725_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='switch_qiwi_updater',
            field=models.BooleanField(default=True),
        ),
    ]
