# Generated by Django 2.1b1 on 2018-07-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180715_2042'),
        ('btcbot', '0004_auto_20180716_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsetting',
            name='api_key',
        ),
        migrations.AddField(
            model_name='adsetting',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKey'),
        ),
    ]
