# Generated by Django 2.1b1 on 2018-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0004_botsetting_switch_qiwi_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsetting',
            name='api_key_qiwi',
            field=models.ManyToManyField(blank=True, to='profiles.APIKeyQiwi'),
        ),
    ]
