# Generated by Django 2.1b1 on 2018-07-16 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0005_auto_20180716_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsetting',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKey'),
            preserve_default=False,
        ),
    ]
