# Generated by Django 2.1b1 on 2018-07-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0006_botsetting_qiwi_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opentrades',
            name='left_review',
        ),
    ]
