# Generated by Django 2.1b1 on 2018-07-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0006_auto_20180716_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsetting',
            name='switch',
        ),
        migrations.AddField(
            model_name='botsetting',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='switch_bot_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='switch_bot_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='switch_bot_send_rev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='switch_buy_ad_upd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='switch_sell_ad_upd',
            field=models.BooleanField(default=False),
        ),
    ]
