# Generated by Django 2.1b1 on 2018-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0008_adsetting_stop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField()),
                ('contragent', models.CharField(max_length=128)),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_btc', models.DecimalField(decimal_places=8, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('reference_text', models.CharField(max_length=256)),
                ('paid', models.BooleanField(default=False)),
                ('disputed', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='botsetting',
            name='switch_bot_send_rev',
        ),
        migrations.AddField(
            model_name='botsetting',
            name='switch_rev_send_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botsetting',
            name='switch_rev_send_sell',
            field=models.BooleanField(default=False),
        ),
    ]
