# Generated by Django 2.1b1 on 2018-08-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0009_remove_botsetting_switch_qiwi_updater'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='all_wallets_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
