# Generated by Django 2.1b1 on 2018-07-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0010_botsetting_telegram_bot_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='is_ad_visible',
            field=models.BooleanField(default=False),
        ),
    ]
