# Generated by Django 2.1b1 on 2018-08-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0010_botsetting_all_wallets_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='meanbuytrades',
            name='is_fee_accounted',
            field=models.BooleanField(default=False),
        ),
    ]
