# Generated by Django 2.1b1 on 2018-07-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0011_botsetting_is_ad_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='need_help',
            field=models.BooleanField(default=False),
        ),
    ]
