# Generated by Django 2.1b1 on 2018-07-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0012_opentrades_need_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='left_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opentrades',
            name='sent_first_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opentrades',
            name='sent_second_message',
            field=models.BooleanField(default=False),
        ),
    ]
