# Generated by Django 2.1b1 on 2018-07-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180722_2355'),
        ('btcbot', '0013_auto_20180723_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='api_key_qiwi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.APIKeyQiwi'),
        ),
    ]
