# Generated by Django 2.1b1 on 2018-08-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0013_opentrades_who_marked_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
