# Generated by Django 2.1b1 on 2018-07-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0014_opentrades_api_key_qiwi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meanbuytrades',
            name='btc_amount',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
    ]
