# Generated by Django 2.1b1 on 2018-08-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0014_opentrades_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='opentrades',
            name='marked_paid',
            field=models.BooleanField(default=False),
        ),
    ]
