# Generated by Django 2.1b1 on 2018-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0015_auto_20180724_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsetting',
            name='qiwi_profit_fee',
            field=models.DecimalField(decimal_places=1, default='1.8', max_digits=2),
        ),
    ]
