# Generated by Django 2.1b1 on 2018-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0016_opentrades_sent_qiwi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meanbuytrades',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opentrades',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
