# Generated by Django 2.1b1 on 2018-07-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0017_botsetting_switch_profit_fixator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opentrades',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='opentrades',
            name='need_help',
        ),
        migrations.AddField(
            model_name='botsetting',
            name='forcefully_released',
            field=models.BooleanField(default=False),
        ),
    ]
