# Generated by Django 2.1b1 on 2018-07-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btcbot', '0018_auto_20180725_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botsetting',
            name='forcefully_released',
        ),
    ]
